name: Cypress ToDo app testcases

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  macos-test:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress docker
        uses: cypress-io/github-action@v2
        with:
          docker: npm run docker
          start: npm start
      - name: Test
        with:
          browser: chrome
          start: npm run dashboard
